### ISSUE TITLE
Note version in exported game state json

### ISSUE THREAD

**Issue by Cealgair** [xxmichaellong/ptcg-sim#18]
I think it can be a good idea to have the version of ptcgsim that the exported game was played on saved somewhere in the json file. This is because, in case any part of it breaks with a future update, someone who really wants to see that game state again at least knows roughly which commit to get back to.

For backwards compatibility, it might be a good idea to put the version somewhere in the game actions, so that importing game states still works in 1.4. Using a game state I have as an example, instead of starting with
```
[
  {
    "user": "self",
    "emit": true,
    "action": "loadDeckData",
    "parameters": [
```
It would start with
```
[
  {
    "ptcgsimVersion": "1.4",
    "user": "self",
    "emit": true,
    "action": "loadDeckData",
    "parameters": [
```
(I'd put the version in each action for good measure, but putting it just in the first one would also be fine)

**Comment by xxmichaellong** [comment]
good idea! Just pushed an update that addresses this.
