### ISSUE TITLE
node.js version

### ISSUE THREAD

**Issue by geiz-12111** [xxmichaellong/ptcg-sim#6]
[2024-01-22T07_40_50_021Z-debug-0.log](https://github.com/xxmichaellong/ptcg-sim/files/14006717/2024-01-22T07_40_50_021Z-debug-0.log)
when I npm install the project ，it's failed.I think my node.js version is wrong. This is the error log.How  can I fix it.

**Comment by xxmichaellong** [comment]
Hi Geiz,

It seems that the installation of the sqlite3 module failed during the npm install process. I no longer use sqlite, so I've updated the list of dependencies.

Please try pulling the latest version of the repository, uninstalling all dependencies, and reinstalling them.

Good luck!

-xxl
