### ISSUE TITLE
有考虑做多语言适配吗

### ISSUE THREAD

**Issue by ruokbb** [xxmichaellong/ptcg-sim#9]
比如中文？现在简中练习急缺平台，tcgone和ptcglive都不太适配了。

**Comment by xxmichaellong** [comment]
Hi! I would be very interested in supporting more international languages. I know that there used to be a Chinese adaptation of PTCG-sim (http://himesakazone.cc/) but it does not seem to be active anymore.

Do you know if there are any good databases of Chinese cards?

Translation:

你好！我非常有兴趣支持更多国际语言。我知道曾经有一个PTCG-sim的中文版本, (http://himesakazone.cc/), 但它似乎不再活跃了。

你知道有没有好的中国卡片数据库吗？

**Comment by ruokbb** [comment]
我是觉得卡片文字保持英文也没关系，这个项目左右ptcg的联系，我相信使用者都是对ptcg很了解的人，可以通过卡图掌握卡片的信息。
目前中国国内有一个kuyo加速器的论坛维护ptcg live的中文补丁包，补丁格式如下：
[xy4_en_105_t.zip](https://github.com/xxmichaellong/ptcg-sim/files/14391527/xy4_en_105_t.zip)

其实只要把网站的文字做多语言适配，可以极大的降低上手难度。目前好像在仓库搜不到i18n相关的函数方法。

Translation:
I think it's okay to keep the card text in English. This project is closely related to the PTCG, and I believe that users are very familiar with PTCG and can understand the card information through the card images.

Currently, there is a forum in China maintaining a Chinese patch for PTCG Live called Kuyo Accelerator. The patch format is as follows: [xy4_en_105_t.zip](https://github.com/xxmichaellong/ptcg-sim/files/14391527/xy4_en_105_t.zip)

In fact, as long as the website's text is adapted for multiple languages, it can greatly reduce the learning curve. Currently, it seems that there are no i18n-related functions or methods in the repository.

**Comment by ruokbb** [comment]
喔，我在Bilibili上找到了你提到的ptcg-sim中文版本，对应的网址是：http://[ptcg.himesakazone.cc](http://ptcg.himesakazone.cc/)/
目前来看是可以正常使用的，还在持续维护。
Translation:
Oh, I found the Chinese version of ptcg-sim you mentioned on Bilibili. The corresponding website is: http://ptcg.himesakazone.cc/
It seems to be working fine and is still being maintained.
